name: provision-infrastructure

on:
  # push:
  #   paths:
  #     - "terraform/**"
  #     - ".github/workflows/infra-provision.yaml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    name: Provision Dev Environment
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Bootstrap Terraform Backend
        shell: pwsh
        run: ./terraform/scripts/bootstrap.ps1

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Set Container Image
        run: echo "TF_VAR_container_image=ghcr.io/${GITHUB_REPOSITORY,,}:latest" >> $GITHUB_ENV

      - name: Terraform Apply (Dev)
        working-directory: terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_location: northeurope
          TF_VAR_container_app_environment_name: dev-env
          TF_VAR_app_name: understand-ms
          TF_VAR_github_username: ${{ secrets.GHCR_USERNAME }}
          TF_VAR_github_pat: ${{ secrets.GHCR_PAT }}